_format_version: "3.0"

services:
  - name: auth-service
    url: http://auth-service:9898
    routes:
      - name: auth-routes
        paths:
          - /auth
        strip_path: false

  - name: user-service
    url: http://user-service:8081
    routes:
      - name: user-routes
        paths:
          - /user
        strip_path: false

  - name: expense-service
    url: http://expense-service:8082
    routes:
      - name: expense-routes
        paths:
          - /expense
        strip_path: false

  - name: ds-service
    url: http://ds-service:3000
    routes:
      - name: ds-routes
        paths:
          - /ds
        strip_path: false
