_format_version: "3.0"

services:
  - name: auth-service
    url: http://auth-service:9898
    routes:
      - name: auth-routes
        paths:
          - /auth
        strip_path: false

  - name: user-service
    url: http://user-service:8081
    plugins:
      - name: forward-auth
        config:
          auth_url: http://auth-service:9898/auth/v1/ping
          timeout_ms: 2000
    routes:
      - name: user-routes
        paths:
          - /user
        strip_path: false

  - name: expense-service
    url: http://expense-service:8082
    plugins:
      - name: forward-auth
        config:
          auth_url: http://auth-service:9898/auth/v1/ping
          timeout_ms: 2000
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Authorization
            - Content-Type
            - Accept
          max_age: 3600
          credentials: false
    routes:
      - name: expense-routes
        paths:
          - /expense
        strip_path: false

  - name: ds-service
    url: http://ds-service:3000
    plugins:
      - name: forward-auth
        config:
          auth_url: http://auth-service:9898/auth/v1/ping
          timeout_ms: 2000
    routes:
      - name: ds-routes
        paths:
          - /ds
        strip_path: false
