FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY dsService/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dsService/src/ .

EXPOSE 3000

CMD ["flask", "--app", "app", "run", "--host=0.0.0.0", "--port=3000"]
