FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY dsService/setup.py dsService/requirements.txt ./
COPY dsService/src/ ./src/
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .

EXPOSE 3000

CMD ["flask", "--app", "app", "run", "--host=0.0.0.0", "--port=3000"]
